const CLIENT_BUILD_PATH = "buildfe"
const SERVER_BUILD_PATH = "build"
const BUILD_TEMP_FOLDER_NAME = '.tmp'
const COMPONENT_ENTRY_PATH = '_COMPONENT_ENTRY_PATH_'
const INJECT_DATA_SCRIPT_ID = '_SCRIPT_ID_'
const WEBPACK_MERGED_CONFIG_TMP = 'webpack.merged.json'
const WEBPACK_EXTERNAL_CONFIG = 'webpack.config.override.js'

export {
  COMPONENT_ENTRY_PATH,
  INJECT_DATA_SCRIPT_ID,
  BUILD_TEMP_FOLDER_NAME,
  SERVER_BUILD_PATH,
  CLIENT_BUILD_PATH,
  WEBPACK_MERGED_CONFIG_TMP,
  WEBPACK_EXTERNAL_CONFIG,
}