const CLIENT_BUILD_PATH = "buildfe"
const SERVER_BUILD_PATH = "build"
const BUILD_TEMP_FOLDER_NAME = '.tmp'
const COMPONENT_ENTRY_PATH = '_COMPONENT_ENTRY_PATH_'
const INJECT_DATA_SCRIPT_ID = '_SCRIPT_ID_'

export {
  COMPONENT_ENTRY_PATH,
  INJECT_DATA_SCRIPT_ID,
  BUILD_TEMP_FOLDER_NAME,
  SERVER_BUILD_PATH,
  CLIENT_BUILD_PATH
}